name: "Terraform CI/CD"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_key }}
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      # Initialize Terraform
      - name: Terraform Init
        id: init
        run: terraform init

      # Plan Terraform
      - name: Terraform Plan
        id: plan
        run: terraform plan

      # Apply Terraform
      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
